# key components
* <font color= #FF0000>function </font> 2021/05/23
* dictionary
* numpy
* matplotlib

# function
* define a block of actions
* use "return" to return result
* pass in parameters

# format

<font color= #FF0000>def </font> [funtion_name] (<font color= #FF0000>parameters </font>):
<br>&emsp;some codes ...<br/>
<font color= #FF0000>&emsp;return ... </font>

In [2]:
def add(a,b):
    c = a+b
    return c

In [6]:
def add(a,b):
    return a+b

In [7]:
x = 1
y = 3

z = add(x,y)

print(z)

4


In [4]:
def print_hello():
    print("hello world")

In [5]:
for i in range(5):
    print_hello()

hello world
hello world
hello world
hello world
hello world


In [8]:
def search_index(input_list, target):
    for idx, num in enumerate(input_list):
        if(num==target):
            return idx
    return -1
            

In [11]:
# search function
test_list = [4,3,6,47,24,65,11]

print(search_index(test_list, 15))

-1


In [21]:
def add1(input_list):
    for idx, num in enumerate(input_list):
        input_list[idx]=input_list[idx]+1
    return input_list

In [22]:
test_list = [4,3,6,47,24,65,11]

print(add1(test_list))

[5, 4, 7, 48, 25, 66, 12]


In [8]:
def new_add1(x):
    x += 1
    return x

In [9]:
#global variable
x = 10
print(x)

# local variable
x = new_add1(x)

print(x)

10
11


In [18]:
date_yd = "2021/0523"
print(date_yd.index("/"))
print(date_yd[4+1:])

4
0523


In [23]:
date_yd = ["2021/0523","2021/0524","2021/0525","2021/0526","2021/0527","2021/0528","2021/0529"]
date_d = []
tmp = date_yd[0][0:date_yd[0].index("/")-1]
print(z)

2021


In [26]:
def removeyear(date_yd):
    for idx, num in enumerate(date_yd):
        date_yd[idx]= date_yd[idx][date_yd[idx].index("/")+1:]
    return date_yd

In [27]:
date_yd = ["2021/0523","2021/0524","2021/0525","2021/0526","2021/0527","2021/0528","2021/0529"]
date=removeyear(date_yd)
print(date)

['0523', '0524', '0525', '0526', '0527', '0528', '0529']


# defalut arguments


In [1]:
def Add(x,y):
    return x+y

In [3]:
x= 10
y= 20

print(Add(10,20))

30


In [7]:
def print_my_notebook(name,year,notebook="windows"):
    print("Hi, {}. Used years: {}, OS:{}".format(name,year,notebook))

SyntaxError: non-default argument follows default argument (<ipython-input-7-04ba43a5b382>, line 1)

In [6]:
print_my_notebook("brian","3")

Hi, brian. Used years: 3, OS:MAC


# dictionary
* list, tuple
* (key,value)
* dict[key] -> value
* ex: ("dog","animal"), ("plane","vehicle"),("person","animal")

In [12]:
tmp_dict = {}
print(type(tmp_dict))

<class 'dict'>


In [13]:
tmp_dict = {"dog":"animal","plane":"vehicle"}

In [15]:
print(tmp_dict["plane"])

vehicle


In [25]:
test = ["a","a","a","a","a","a","a","b","b","b","b","b"]

count_dict = {}

for i in test:
    count_dict.setdefault(i,0)
    print(count_dict)
    count_dict[i]+=1;

{'a': 0}
{'a': 1}
{'a': 2}
{'a': 3}
{'a': 4}
{'a': 5}
{'a': 6}
{'a': 7, 'b': 0}
{'a': 7, 'b': 1}
{'a': 7, 'b': 2}
{'a': 7, 'b': 3}
{'a': 7, 'b': 4}


In [24]:
print(count_dict)

{'a': 7, 'b': 5}


In [28]:
import numpy as np
np.random.seed(1)

test = np.random.randint(-100,100,30)

In [30]:
print(test)

[-63  40 -28  37  33 -21  92  44  29 -29  34 -75  78 -80   1  46  39  56
  57  42 -50 -32  -4 -14  41  37 -93 -37 -39 -78 -43 -99  28 -40 -92  41
  15  75  21 -70 -29  31  98  49 -51 -43 -97  96 -76 -57 -24 -74 -48 -20
   9  15 -59 -85 -36  96 -75  11  35 -74  53   4 -78 -91  95  26 -77  25
   0  55  65 -43 -17  66  36 -68  62 -90 -77  43 -13 -75  99  -8 -26  90
 -54  60  51  83 -35  13 -23 -97  28 -94]


design two functions
1. dictionary [key: number, value: times]
2. input (2numbers) -> output (2,times)

(-63,40) -> (1,4)


In [31]:
tmp_dict = {"dog": [1,2,353],"plane":"vehicle"}
print(tmp_dict)

{'dog': [1, 2, 353], 'plane': 'vehicle'}


In [32]:
tmp_dict_2 = {"dict1":tmp_dict}
print(tmp_dict_2)

{'dict1': {'dog': [1, 2, 353], 'plane': 'vehicle'}}


# numpy
* array, matrix

In [ ]:
import numpy as np

In [38]:
test_list = [1,2,3,4,6,7]
print(type(test_list))
test_list = test_list*2
print(test_list)

<class 'list'>
[1, 2, 3, 4, 6, 7, 1, 2, 3, 4, 6, 7]


In [35]:
test_numpy = np.array(test_list)
print(type(test_numpy))
print(test_numpy)

<class 'numpy.ndarray'>
[1 2 3 4 6 7]


In [36]:
test_numpy = test_numpy*2
print(test_numpy)

[ 2  4  6  8 12 14]


In [40]:
print(test_numpy[test_numpy>=6])

[ 6  8 12 14]


# open file

In [41]:
import numpy as np
import os

data_path = "./data/"
file_name ="all-states-history.csv"
file_path = os.path.join(data_path,file_name)
print(file_path)

./data/all-states-history.csv


In [64]:
data = np.loadtxt(file_path, delimiter=',',dtype= np.str)
print(data[0])

['"date"' '"state"' '"death"' '"deathConfirmed"' '"deathIncrease"'
 '"deathProbable"' '"hospitalized"' '"hospitalizedCumulative"'
 '"hospitalizedCurrently"' '"hospitalizedIncrease"' '"inIcuCumulative"'
 '"inIcuCurrently"' '"negative"' '"negativeIncrease"'
 '"negativeTestsAntibody"' '"negativeTestsPeopleAntibody"'
 '"negativeTestsViral"' '"onVentilatorCumulative"'
 '"onVentilatorCurrently"' '"positive"' '"positiveCasesViral"'
 '"positiveIncrease"' '"positiveScore"' '"positiveTestsAntibody"'
 '"positiveTestsAntigen"' '"positiveTestsPeopleAntibody"'
 '"positiveTestsPeopleAntigen"' '"positiveTestsViral"' '"recovered"'
 '"totalTestEncountersViral"' '"totalTestEncountersViralIncrease"'
 '"totalTestResults"' '"totalTestResultsIncrease"' '"totalTestsAntibody"'
 '"totalTestsAntigen"' '"totalTestsPeopleAntibody"'
 '"totalTestsPeopleAntigen"' '"totalTestsPeopleViral"'
 '"totalTestsPeopleViralIncrease"' '"totalTestsViral"'
 '"totalTestsViralIncrease"']


In [95]:
data[data==""] = 0
data_flip = np.flip(data,0)
print(data_flip[-1])
print(data_flip[0])

['"date"' '"state"' '"death"' '"deathConfirmed"' '"deathIncrease"'
 '"deathProbable"' '"hospitalized"' '"hospitalizedCumulative"'
 '"hospitalizedCurrently"' '"hospitalizedIncrease"' '"inIcuCumulative"'
 '"inIcuCurrently"' '"negative"' '"negativeIncrease"'
 '"negativeTestsAntibody"' '"negativeTestsPeopleAntibody"'
 '"negativeTestsViral"' '"onVentilatorCumulative"'
 '"onVentilatorCurrently"' '"positive"' '"positiveCasesViral"'
 '"positiveIncrease"' '"positiveScore"' '"positiveTestsAntibody"'
 '"positiveTestsAntigen"' '"positiveTestsPeopleAntibody"'
 '"positiveTestsPeopleAntigen"' '"positiveTestsViral"' '"recovered"'
 '"totalTestEncountersViral"' '"totalTestEncountersViralIncrease"'
 '"totalTestResults"' '"totalTestResultsIncrease"' '"totalTestsAntibody"'
 '"totalTestsAntigen"' '"totalTestsPeopleAntibody"'
 '"totalTestsPeopleAntigen"' '"totalTestsPeopleViral"'
 '"totalTestsPeopleViralIncrease"' '"totalTestsViral"'
 '"totalTestsViralIncrease"']
['"2020-01-13"' '"WA"' '0' '0' '0' '0' '0' '0

# use date to divide

In [96]:
organized_data = {}

for row in data_flip[:-1]:
    date = row[0][1:-1]
    state = row[1][1:-1]
    organized_data.setdefault(date,{})
    organized_data[date].setdefault(state,[])
    organized_data[date][state].extend(row[2:].astype(np.int32))


print(organized_data["2021-03-07"]["AK"])

[305, 0, 0, 0, 1293, 1293, 33, 0, 0, 0, 0, 0, 0, 0, 1660758, 0, 2, 56886, 0, 0, 0, 0, 0, 0, 0, 68693, 0, 0, 0, 1731628, 0, 0, 0, 0, 0, 0, 0, 1731628, 0]


In [97]:
dates = organized_data.keys()
states = organized_data["2021-03-07"].keys()
print(dates)
print(states)

dict_keys(['2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16', '2020-01-17', '2020-01-18', '2020-01-19', '2020-01-20', '2020-01-21', '2020-01-22', '2020-01-23', '2020-01-24', '2020-01-25', '2020-01-26', '2020-01-27', '2020-01-28', '2020-01-29', '2020-01-30', '2020-01-31', '2020-02-01', '2020-02-02', '2020-02-03', '2020-02-04', '2020-02-05', '2020-02-06', '2020-02-07', '2020-02-08', '2020-02-09', '2020-02-10', '2020-02-11', '2020-02-12', '2020-02-13', '2020-02-14', '2020-02-15', '2020-02-16', '2020-02-17', '2020-02-18', '2020-02-19', '2020-02-20', '2020-02-21', '2020-02-22', '2020-02-23', '2020-02-24', '2020-02-25', '2020-02-26', '2020-02-27', '2020-02-28', '2020-02-29', '2020-03-01', '2020-03-02', '2020-03-03', '2020-03-04', '2020-03-05', '2020-03-06', '2020-03-07', '2020-03-08', '2020-03-09', '2020-03-10', '2020-03-11', '2020-03-12', '2020-03-13', '2020-03-14', '2020-03-15', '2020-03-16', '2020-03-17', '2020-03-18', '2020-03-19', '2020-03-20', '2020-03-21', '2020-03-22', '2020-03-

In [102]:
Death_WithDates = {}

for date_key, date_value in organized_data.items() :
    for state_key, state_value in organized_data[date_key].items():
        Death_WithDates.setdefault(state_key,[])
        Death_WithDates[state_key].append(state_value[0])

print(Death_WithDates)

{'WA': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 4, 5, 8, 11, 14, 16, 20, 26, 27, 31, 35, 37, 40, 44, 47, 51, 57, 69, 78, 82, 92, 104, 111, 126, 137, 146, 159, 183, 199, 220, 237, 248, 262, 282, 310, 338, 365, 386, 407, 429, 443, 459, 476, 494, 509, 526, 542, 551, 571, 585, 598, 615, 629, 640, 647, 654, 659, 665, 738, 749, 765, 786, 801, 814, 824, 830, 834, 841, 862, 870, 891, 905, 921, 931, 945, 962, 975, 983, 992, 1000, 1001, 1002, 1031, 1037, 1044, 1050, 1055, 1061, 1070, 1078, 1095, 1106, 1111, 1118, 1118, 1124, 1129, 1135, 1138, 1149, 1153, 1159, 1161, 1176, 1190, 1194, 1204, 1213, 1217, 1221, 1231, 1226, 1245, 1255, 1265, 1270, 1276, 1284, 1293, 1300, 1304, 1310, 1310, 1320, 1332, 1339, 1342, 1352, 1354, 1359, 1370, 1384, 1394, 1409, 1424, 1424, 1438, 1399, 1404, 1421, 1427, 1434, 1444, 1447, 1453, 1465, 1468, 1482, 1495, 1494, 1501, 1518, 1548, 1555, 1564, 1564, 1592, 1596, 1600, 161

In [105]:
import matplotlib.pyplot as plt
for key,value in Death_WithDates.items():
    print(key,len(value))
# plt.plot(Death_WithDates["AK"])
# plt.show()

WA 420
MA 411
VA 406
FL 404
NJ 392
NE 387
IN 375
CT 373
WY 372
RI 372
MI 372
NY 371
WI 370
VT 370
TX 370
PA 370
SC 369
OR 369
NH 369
NC 369
IL 369
HI 369
GA 369
CO 369
CA 369
AZ 369
TN 368
OH 368
NV 368
NM 368
MD 368
DC 368
WV 367
MN 367
KY 367
KS 367
IA 367
DE 367
AR 367
AK 367
UT 366
SD 366
OK 366
ND 366
MT 366
MS 366
MO 366
ME 366
LA 366
ID 366
AL 366
VI 357
PR 357
MP 357
GU 357
AS 357
